
SET IDENTITY_INSERT Config.CarMake ON

INSERT INTO Config.CarMake(CarMakeId,Name)Values(1,'Abarth')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(2,'Alfa Romeo')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(3,'Aro')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(4,'Asia')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(5,'Asia Motors')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(6,'Aston Martin')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(7,'Audi')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(8,'Austin')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(9,'Auverland')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(10,'Bentley')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(11,'Bertone')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(12,'Bmw')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(13,'Cadillac')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(14,'Chevrolet')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(15,'Chrysler')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(16,'Citroen')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(17,'Corvette')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(18,'Dacia')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(19,'Daewoo')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(20,'Daf')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(21,'Daihatsu')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(22,'Daimler')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(23,'Dodge')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(24,'Ferrari')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(25,'Fiat')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(26,'Ford')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(27,'Galloper')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(28,'Gmc')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(29,'Honda')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(30,'Hummer')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(31,'Hyundai')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(32,'Infiniti')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(33,'Innocenti')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(34,'Isuzu')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(35,'Iveco')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(36,'Iveco-pegaso')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(37,'Jaguar')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(38,'Jeep')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(39,'Kia')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(40,'Lada')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(41,'Lamborghini')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(42,'Lancia')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(43,'Land-rover')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(44,'Ldv')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(45,'Lexus')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(46,'Lotus')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(47,'Mahindra')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(48,'Maserati')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(49,'Maybach')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(50,'Mazda')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(51,'Mercedes-benz')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(52,'Mg')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(53,'Mini')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(54,'Mitsubishi')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(55,'Morgan')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(56,'Nissan')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(57,'Opel')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(58,'Peugeot')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(59,'Pontiac')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(60,'Porsche')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(61,'Renault')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(62,'Rolls-royce')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(63,'Rover')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(64,'Saab')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(65,'Santana')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(66,'Seat')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(67,'Skoda')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(68,'Smart')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(69,'Ssangyong')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(70,'Subaru')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(71,'Suzuki')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(72,'Talbot')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(73,'Tata')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(74,'Toyota')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(75,'Umm')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(76,'Vaz')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(77,'Volkswagen')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(78,'Volvo')
INSERT INTO Config.CarMake(CarMakeId,Name)Values(79,'Wartburg')

SET IDENTITY_INSERT Config.CarMake OFF