SET IDENTITY_INSERT Config.CarModel ON

INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(1,1,'500')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(1,2,'Grande Punto')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(1,3,'Punto Evo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(1,4,'500c')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(1,5,'695')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(1,6,'Punto')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(2,7,'155')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(2,8,'156')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(2,9,'159')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(2,10,'164')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(2,11,'145')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(2,12,'147')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(2,13,'146')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(2,14,'Gtv')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(2,15,'Spider')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(2,16,'166')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(2,17,'Gt')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(2,18,'Crosswagon')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(2,19,'Brera')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(2,20,'90')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(2,21,'75')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(2,22,'33')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(2,23,'Giulietta')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(2,24,'Sprint')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(2,25,'Mito')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(3,26,'Expander')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(3,27,'10')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(3,28,'24')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(3,29,'Dacia')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(4,30,'Rocsta')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(5,31,'Rocsta')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(6,32,'Db7')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(6,33,'V8')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(6,34,'Db9')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(6,35,'Vanquish')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(6,36,'V8 Vantage')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(6,37,'Vantage')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(6,38,'Dbs')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(6,39,'Volante')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(6,40,'Virage')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(6,41,'Vantage V8')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(6,42,'Vantage V12')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(6,43,'Rapide')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(6,44,'Cygnet')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,45,'80')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,46,'A4')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,47,'A6')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,48,'S6')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,49,'Coupe')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,50,'S2')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,51,'Rs2')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,52,'A8')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,53,'Cabriolet')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,54,'S8')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,55,'A3')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,56,'S4')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,57,'Tt')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,58,'S3')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,59,'Allroad Quattro')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,60,'Rs4')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,61,'A2')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,62,'Rs6')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,63,'Q7')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,64,'R8')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,65,'A5')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,66,'S5')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,67,'V8')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,68,'200')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,69,'100')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,70,'90')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,71,'Tts')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,72,'Q5')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,73,'A4 Allroad Quattro')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,74,'Tt Rs')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,75,'Rs5')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,76,'A1')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,77,'A7')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,78,'Rs3')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,79,'Q3')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,80,'A6 Allroad Quattro')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,81,'S7')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(7,82,'Sq5')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(8,83,'Mini')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(8,84,'Montego')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(8,85,'Maestro')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(8,86,'Metro')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(8,87,'Mini Moke')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(9,88,'Diesel')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(10,89,'Brooklands')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(10,90,'Turbo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(10,91,'Continental')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(10,92,'Azure')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(10,93,'Arnage')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(10,94,'Continental Gt')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(10,95,'Continental Flying Spur')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(10,96,'Turbo R')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(10,97,'Mulsanne')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(10,98,'Eight')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(10,99,'Continental Gtc')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(10,100,'Continental Supersports')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(11,101,'Freeclimber Diesel')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(12,102,'Serie 3')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(12,103,'Serie 5')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(12,104,'Compact')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(12,105,'Serie 7')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(12,106,'Serie 8')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(12,107,'Z3')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(12,108,'Z4')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(12,109,'Z8')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(12,110,'X5')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(12,111,'Serie 6')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(12,112,'X3')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(12,113,'Serie 1')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(12,114,'Z1')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(12,115,'X6')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(12,116,'X1')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(13,117,'Seville')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(13,118,'Sts')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(13,119,'El Dorado')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(13,120,'Cts')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(13,121,'Xlr')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(13,122,'Srx')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(13,123,'Escalade')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(13,124,'Bls')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(14,125,'Corvette')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(14,126,'Blazer')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(14,127,'Astro')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(14,128,'Nubira')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(14,129,'Evanda')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(14,130,'Trans Sport')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(14,131,'Camaro')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(14,132,'Matiz')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(14,133,'Alero')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(14,134,'Tahoe')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(14,135,'Tacuma')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(14,136,'Trailblazer')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(14,137,'Kalos')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(14,138,'Aveo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(14,139,'Lacetti')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(14,140,'Epica')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(14,141,'Captiva')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(14,142,'Hhr')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(14,143,'Cruze')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(14,144,'Spark')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(14,145,'Orlando')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(14,146,'Volt')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(14,147,'Malibu')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(15,148,'Vision')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(15,149,'300m')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(15,150,'Grand Voyager')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(15,151,'Viper')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(15,152,'Neon')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(15,153,'Voyager')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(15,154,'Stratus')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(15,155,'Sebring')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(15,156,'Sebring 200c')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(15,157,'New Yorker')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(15,158,'Pt Cruiser')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(15,159,'Crossfire')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(15,160,'300c')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(15,161,'Le Baron')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(15,162,'Saratoga')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,163,'Xantia')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,164,'Xm')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,165,'Ax')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,166,'Zx')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,167,'Evasion')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,168,'C8')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,169,'Saxo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,170,'C2')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,171,'Xsara')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,172,'C4')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,173,'Xsara Picasso')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,174,'C5')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,175,'C3')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,176,'C3 Pluriel')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,177,'C1')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,178,'C6')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,179,'Grand C4 Picasso')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,180,'C4 Picasso')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,181,'Ccrosser')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,182,'C15')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,183,'Jumper')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,184,'Jumpy')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,185,'Berlingo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,186,'Bx')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,187,'C25')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,188,'Cx')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,189,'Gsa')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,190,'Visa')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,191,'Lna')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,192,'2cv')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,193,'Nemo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,194,'C4 Sedan')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,195,'Berlingo First')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,196,'C3 Picasso')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,197,'Ds3')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,198,'Czero')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,199,'Ds4')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,200,'Ds5')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,201,'C4 Aircross')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(16,202,'Celysee')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(17,203,'Corvette')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(18,204,'Contac')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(18,205,'Logan')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(18,206,'Sandero')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(18,207,'Duster')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(18,208,'Lodgy')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(19,209,'Nexia')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(19,210,'Aranos')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(19,211,'Lanos')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(19,212,'Nubira')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(19,213,'Compact')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(19,214,'Nubira Compact')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(19,215,'Leganza')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(19,216,'Evanda')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(19,217,'Matiz')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(19,218,'Tacuma')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(19,219,'Kalos')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(19,220,'Lacetti')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(21,221,'Applause')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(21,222,'Charade')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(21,223,'Rocky')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(21,224,'Feroza')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(21,225,'Terios')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(21,226,'Sirion')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(22,227,'Serie Xj')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(22,228,'Xj')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(22,229,'Double Six')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(22,230,'Six')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(22,231,'Series Iii')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(23,232,'Viper')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(23,233,'Caliber')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(23,234,'Nitro')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(23,235,'Avenger')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(23,236,'Journey')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,237,'F355')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,238,'360')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,239,'F430')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,240,'F512 M')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,241,'550 Maranello')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,242,'575m Maranello')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,243,'599')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,244,'456')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,245,'456m')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,246,'612')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,247,'F50')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,248,'Enzo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,249,'Superamerica')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,250,'430')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,251,'348')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,252,'Testarossa')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,253,'512')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,254,'355')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,255,'F40')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,256,'412')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,257,'Mondial')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,258,'328')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,259,'California')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,260,'458')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(24,261,'Ff')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,262,'Croma')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,263,'Cinquecento')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,264,'Seicento')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,265,'Punto')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,266,'Grande Punto')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,267,'Panda')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,268,'Tipo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,269,'Coupe')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,270,'Uno')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,271,'Ulysse')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,272,'Tempra')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,273,'Marea')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,274,'Barchetta')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,275,'Bravo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,276,'Stilo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,277,'Brava')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,278,'Palio Weekend')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,279,'600')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,280,'Multipla')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,281,'Idea')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,282,'Sedici')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,283,'Linea')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,284,'500')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,285,'Fiorino')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,286,'Ducato')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,287,'Doblo Cargo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,288,'Doblo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,289,'Strada')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,290,'Regata')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,291,'Talento')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,292,'Argenta')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,293,'Ritmo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,294,'Punto Classic')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,295,'Qubo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,296,'Punto Evo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,297,'500c')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,298,'Freemont')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,299,'Panda Classic')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(25,300,'500l')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,301,'Maverick')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,302,'Escort')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,303,'Focus')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,304,'Mondeo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,305,'Scorpio')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,306,'Fiesta')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,307,'Probe')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,308,'Explorer')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,309,'Galaxy')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,310,'Ka')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,311,'Puma')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,312,'Cougar')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,313,'Focus Cmax')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,314,'Fusion')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,315,'Streetka')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,316,'Cmax')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,317,'Smax')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,318,'Transit')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,319,'Courier')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,320,'Ranger')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,321,'Sierra')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,322,'Orion')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,323,'Pick Up')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,324,'Capri')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,325,'Granada')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,326,'Kuga')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,327,'Grand Cmax')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,328,'Bmax')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(26,329,'Tourneo Custom')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(27,330,'Exceed')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(27,331,'Santamo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(27,332,'Super Exceed')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(29,333,'Accord')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(29,334,'Civic')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(29,335,'Crx')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(29,336,'Prelude')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(29,337,'Nsx')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(29,338,'Legend')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(29,339,'Crv')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(29,340,'Hrv')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(29,341,'Logo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(29,342,'S2000')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(29,343,'Stream')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(29,344,'Jazz')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(29,345,'Frv')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(29,346,'Concerto')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(29,347,'Insight')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(29,348,'Crz')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(30,349,'H2')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(30,350,'H3')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(30,351,'H3t')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,352,'Lantra')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,353,'Sonata')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,354,'Elantra')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,355,'Accent')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,356,'Scoupe')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,357,'Coupe')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,358,'Atos')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,359,'H1')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,360,'Atos Prime')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,361,'Xg')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,362,'Trajet')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,363,'Santa Fe')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,364,'Terracan')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,365,'Matrix')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,366,'Getz')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,367,'Tucson')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,368,'I30')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,369,'Pony')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,370,'Grandeur')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,371,'I10')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,372,'I800')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,373,'Sonata Fl')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,374,'Ix55')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,375,'I20')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,376,'Ix35')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,377,'Ix20')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,378,'Genesis')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,379,'I40')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(31,380,'Veloster')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(32,381,'G')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(32,382,'Ex')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(32,383,'Fx')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(32,384,'M')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(33,385,'Elba')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(33,386,'Minitre')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(34,387,'Trooper')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(34,388,'Pick Up')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(34,389,'D Max')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(34,390,'Rodeo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(34,391,'Dmax')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(34,392,'Trroper')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(35,393,'Daily')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(35,394,'Massif')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(36,395,'Daily')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(36,396,'Duty')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(37,397,'Serie Xj')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(37,398,'Serie Xk')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(37,399,'Xj')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(37,400,'Stype')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(37,401,'Xf')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(37,402,'Xtype')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(38,403,'Wrangler')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(38,404,'Cherokee')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(38,405,'Grand Cherokee')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(38,406,'Commander')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(38,407,'Compass')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(38,408,'Wrangler Unlimited')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(38,409,'Patriot')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,410,'Sportage')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,411,'Sephia')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,412,'Sephia Ii')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,413,'Pride')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,414,'Clarus')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,415,'Shuma')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,416,'Carnival')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,417,'Joice')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,418,'Magentis')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,419,'Carens')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,420,'Rio')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,421,'Cerato')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,422,'Sorento')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,423,'Opirus')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,424,'Picanto')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,425,'Ceed')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,426,'Ceed Sporty Wagon')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,427,'Proceed')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,428,'K2500 Frontier')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,429,'K2500')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,430,'Soul')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,431,'Venga')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,432,'Optima')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(39,433,'Ceed Sportswagon')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(40,434,'Samara')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(40,435,'Niva')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(40,436,'Sagona')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(40,437,'Stawra 2110')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(40,438,'214')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(40,439,'Kalina')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(40,440,'Serie 2100')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(40,441,'Priora')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(41,442,'Gallardo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(41,443,'Murcielago')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(41,444,'Aventador')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(42,445,'Delta')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(42,446,'K')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(42,447,'Y10')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(42,448,'Dedra')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(42,449,'Lybra')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(42,450,'Z')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(42,451,'Y')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(42,452,'Ypsilon')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(42,453,'Thesis')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(42,454,'Phedra')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(42,455,'Musa')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(42,456,'Thema')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(42,457,'Zeta')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(42,458,'Kappa')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(42,459,'Trevi')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(42,460,'Prisma')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(42,461,'A112')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(42,462,'Ypsilon Elefantino')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(42,463,'Voyager')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(43,464,'Range Rover')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(43,465,'Defender')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(43,466,'Discovery')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(43,467,'Freelander')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(43,468,'Range Rover Sport')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(43,469,'Discovery 4')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(43,470,'Range Rover Evoque')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(44,471,'Maxus')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(45,472,'Ls400')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(45,473,'Ls430')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(45,474,'Gs300')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(45,475,'Is200')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(45,476,'Rx300')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(45,477,'Gs430')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(45,478,'Gs460')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(45,479,'Sc430')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(45,480,'Is300')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(45,481,'Is250')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(45,482,'Rx400h')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(45,483,'Is220d')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(45,484,'Rx350')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(45,485,'Gs450h')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(45,486,'Ls460')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(45,487,'Ls600h')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(45,488,'Ls')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(45,489,'Gs')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(45,490,'Is')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(45,491,'Sc')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(45,492,'Rx')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(45,493,'Ct')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(46,494,'Elise')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(46,495,'Exige')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(47,496,'Bolero Pickup')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(47,497,'Goa Pickup')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(47,498,'Goa')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(47,499,'Cj')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(47,500,'Pikup')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(47,501,'Thar')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(48,502,'Ghibli')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(48,503,'Shamal')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(48,504,'Quattroporte')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(48,505,'3200 Gt')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(48,506,'Coupe')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(48,507,'Spyder')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(48,508,'Gransport')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(48,509,'Granturismo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(48,510,'430')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(48,511,'Biturbo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(48,512,'228')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(48,513,'224')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(48,514,'Grancabrio')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(49,515,'Maybach')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,516,'Xedos 6')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,517,'626')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,518,'121')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,519,'Xedos 9')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,520,'323')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,521,'Mx3')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,522,'Rx7')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,523,'Mx5')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,524,'Mazda3')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,525,'Mpv')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,526,'Demio')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,527,'Premacy')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,528,'Tribute')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,529,'Mazda6')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,530,'Mazda2')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,531,'Rx8')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,532,'Mazda5')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,533,'Cx7')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,534,'Serie B')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,535,'B2500')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,536,'Bt50')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,537,'Mx6')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,538,'929')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(50,539,'Cx5')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,540,'Clase C')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,541,'Clase E')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,542,'Clase Sl')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,543,'Clase S')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,544,'Clase Cl')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,545,'Clase G')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,546,'Clase Slk')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,547,'Clase V')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,548,'Viano')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,549,'Clase Clk')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,550,'Clase A')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,551,'Clase M')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,552,'Vaneo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,553,'Slklasse')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,554,'Slr Mclaren')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,555,'Clase Cls')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,556,'Clase R')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,557,'Clase Gl')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,558,'Clase B')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,559,'100d')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,560,'140d')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,561,'180d')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,562,'Sprinter')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,563,'Vito')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,564,'Transporter')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,565,'280')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,566,'220')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,567,'200')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,568,'190')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,569,'600')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,570,'400')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,571,'Clase Sl R129')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,572,'300')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,573,'500')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,574,'420')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,575,'260')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,576,'230')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,577,'Clase Clc')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,578,'Clase Glk')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(51,579,'Sls Amg')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(52,580,'Mgf')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(52,581,'Tf')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(52,582,'Zr')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(52,583,'Zs')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(52,584,'Zt')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(52,585,'Ztt')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(52,586,'Mini')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(52,587,'Countryman')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(52,588,'Paceman')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(54,589,'Montero')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(54,590,'Galant')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(54,591,'Colt')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(54,592,'Space Wagon')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(54,593,'Space Runner')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(54,594,'Space Gear')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(54,595,'3000 Gt')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(54,596,'Carisma')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(54,597,'Eclipse')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(54,598,'Space Star')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(54,599,'Montero Sport')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(54,600,'Montero Io')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(54,601,'Outlander')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(54,602,'Lancer')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(54,603,'Grandis')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(54,604,'L200')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(54,605,'Canter')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(54,606,'300 Gt')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(54,607,'Asx')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(54,608,'Imiev')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(55,609,'44')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(55,610,'Plus 8')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(55,611,'Aero 8')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(55,612,'V6')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(55,613,'Roadster')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(55,614,'4')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(55,615,'Plus 4')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,616,'Terrano Ii')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,617,'Terrano')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,618,'Micra')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,619,'Sunny')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,620,'Primera')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,621,'Serena')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,622,'Patrol')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,623,'Maxima Qx')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,624,'200 Sx')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,625,'300 Zx')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,626,'Patrol Gr')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,627,'100 Nx')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,628,'Almera')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,629,'Pathfinder')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,630,'Almera Tino')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,631,'Xtrail')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,632,'350z')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,633,'Murano')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,634,'Note')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,635,'Qashqai')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,636,'Tiida')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,637,'Vanette')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,638,'Trade')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,639,'Vanette Cargo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,640,'Pickup')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,641,'Navara')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,642,'Cabstar E')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,643,'Cabstar')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,644,'Maxima')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,645,'Camion')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,646,'Prairie')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,647,'Bluebird')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,648,'Np300 Pick Up')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,649,'Qashqai2')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,650,'Pixo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,651,'Gtr')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,652,'370z')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,653,'Cube')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,654,'Juke')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,655,'Leaf')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(56,656,'Evalia')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,657,'Astra')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,658,'Vectra')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,659,'Calibra')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,660,'Corsa')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,661,'Omega')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,662,'Frontera')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,663,'Tigra')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,664,'Monterey')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,665,'Sintra')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,666,'Zafira')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,667,'Agila')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,668,'Speedster')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,669,'Signum')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,670,'Meriva')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,671,'Antara')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,672,'Gt')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,673,'Combo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,674,'Movano')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,675,'Vivaro')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,676,'Kadett')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,677,'Monza')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,678,'Senator')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,679,'Rekord')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,680,'Manta')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,681,'Ascona')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,682,'Insignia')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,683,'Zafira Tourer')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,684,'Ampera')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,685,'Mokka')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(57,686,'Adam')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,687,'306')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,688,'605')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,689,'106')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,690,'205')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,691,'405')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,692,'406')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,693,'806')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,694,'807')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,695,'407')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,696,'307')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,697,'206')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,698,'607')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,699,'308')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,700,'307 Sw')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,701,'206 Sw')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,702,'407 Sw')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,703,'1007')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,704,'107')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,705,'207')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,706,'4007')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,707,'Boxer')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,708,'Partner')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,709,'J5')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,710,'604')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,711,'505')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,712,'309')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,713,'Bipper')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,714,'Partner Origin')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,715,'3008')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,716,'5008')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,717,'Rcz')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,718,'508')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,719,'Ion')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,720,'208')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(58,721,'4008')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(59,722,'Trans Sport')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(59,723,'Firebird')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(59,724,'Trans Am')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(60,725,'911')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(60,726,'Boxster')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(60,727,'Cayenne')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(60,728,'Carrera Gt')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(60,729,'Cayman')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(60,730,'928')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(60,731,'968')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(60,732,'944')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(60,733,'924')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(60,734,'Panamera')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(60,735,'918')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,736,'Megane')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,737,'Safrane')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,738,'Laguna')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,739,'Clio')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,740,'Twingo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,741,'Nevada')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,742,'Espace')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,743,'Spider')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,744,'Scenic')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,745,'Grand Espace')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,746,'Avantime')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,747,'Vel Satis')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,748,'Grand Scenic')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,749,'Clio Campus')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,750,'Modus')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,751,'Express')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,752,'Trafic')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,753,'Master')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,754,'Kangoo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,755,'Mascott')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,756,'Master Propulsion')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,757,'Maxity')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,758,'R19')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,759,'R25')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,760,'R5')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,761,'R21')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,762,'R4')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,763,'Alpine')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,764,'Fuego')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,765,'R18')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,766,'R11')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,767,'R9')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,768,'R6')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,769,'Grand Modus')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,770,'Kangoo Combi')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,771,'Koleos')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,772,'Fluence')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,773,'Wind')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,774,'Latitude')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(61,775,'Grand Kangoo Combi')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(62,776,'Siver Dawn')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(62,777,'Silver Spur')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(62,778,'Park Ward')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(62,779,'Silver Seraph')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(62,780,'Corniche')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(62,781,'Phantom')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(62,782,'Touring')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(62,783,'Silvier')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(63,784,'800')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(63,785,'600')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(63,786,'100')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(63,787,'200')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(63,788,'Coupe')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(63,789,'400')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(63,790,'45')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(63,791,'Cabriolet')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(63,792,'25')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(63,793,'Mini')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(63,794,'75')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(63,795,'Streetwise')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(63,796,'Sd')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(64,797,'900')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(64,798,'93')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(64,799,'9000')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(64,800,'95')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(64,801,'93x')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(64,802,'94x')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(65,803,'300')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(65,804,'350')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(65,805,'Anibal')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(65,806,'Anibal Pick Up')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(66,807,'Ibiza')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(66,808,'Cordoba')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(66,809,'Toledo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(66,810,'Marbella')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(66,811,'Alhambra')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(66,812,'Arosa')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(66,813,'Leon')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(66,814,'Altea')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(66,815,'Altea Xl')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(66,816,'Altea Freetrack')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(66,817,'Terra')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(66,818,'Inca')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(66,819,'Malaga')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(66,820,'Ronda')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(66,821,'Exeo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(66,822,'Mii')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(67,823,'Felicia')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(67,824,'Forman')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(67,825,'Octavia')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(67,826,'Octavia Tour')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(67,827,'Fabia')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(67,828,'Superb')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(67,829,'Roomster')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(67,830,'Scout')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(67,831,'Pickup')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(67,832,'Favorit')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(67,833,'130')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(67,834,'S')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(67,835,'Yeti')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(67,836,'Citigo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(67,837,'Rapid')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(68,838,'Smart')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(68,839,'Citycoupe')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(68,840,'Fortwo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(68,841,'Cabrio')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(68,842,'Crossblade')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(68,843,'Roadster')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(68,844,'Forfour')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(69,845,'Korando')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(69,846,'Family')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(69,847,'K4d')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(69,848,'Musso')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(69,849,'Korando Kj')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(69,850,'Rexton')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(69,851,'Rexton Ii')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(69,852,'Rodius')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(69,853,'Kyron')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(69,854,'Actyon')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(69,855,'Sports Pick Up')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(69,856,'Actyon Sports Pick Up')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(69,857,'Kodando')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(70,858,'Legacy')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(70,859,'Impreza')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(70,860,'Svx')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(70,861,'Justy')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(70,862,'Outback')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(70,863,'Forester')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(70,864,'G3x Justy')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(70,865,'B9 Tribeca')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(70,866,'Xt')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(70,867,'1800')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(70,868,'Tribeca')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(70,869,'Wrx Sti')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(70,870,'Trezia')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(70,871,'Xv')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(70,872,'Brz')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(71,873,'Maruti')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(71,874,'Swift')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(71,875,'Vitara')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(71,876,'Baleno')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(71,877,'Samurai')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(71,878,'Alto')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(71,879,'Wagon R')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(71,880,'Jimny')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(71,881,'Grand Vitara')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(71,882,'Ignis')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(71,883,'Liana')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(71,884,'Grand Vitara Xl7')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(71,885,'Sx4')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(71,886,'Splash')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(71,887,'Kizashi')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(72,888,'Samba')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(72,889,'Tagora')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(72,890,'Solara')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(72,891,'Horizon')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(73,892,'Telcosport')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(73,893,'Telco')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(73,894,'Sumo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(73,895,'Safari')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(73,896,'Indica')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(73,897,'Indigo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(73,898,'Grand Safari')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(73,899,'Tl Pick Up')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(73,900,'Xenon Pick Up')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(73,901,'Vista')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(73,902,'Xenon')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(73,903,'Aria')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,904,'Carina E')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,905,'4runner')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,906,'Camry')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,907,'Rav4')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,908,'Celica')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,909,'Supra')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,910,'Paseo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,911,'Land Cruiser 80')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,912,'Land Cruiser 100')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,913,'Land Cruiser')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,914,'Land Cruiser 90')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,915,'Corolla')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,916,'Auris')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,917,'Avensis')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,918,'Picnic')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,919,'Yaris')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,920,'Yaris Verso')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,921,'Mr2')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,922,'Previa')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,923,'Prius')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,924,'Avensis Verso')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,925,'Corolla Verso')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,926,'Corolla Sedan')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,927,'Aygo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,928,'Hilux')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,929,'Dyna')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,930,'Land Cruiser 200')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,931,'Verso')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,932,'Iq')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,933,'Urban Cruiser')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(74,934,'Gt86')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(75,935,'100')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(75,936,'121')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(76,937,'214')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(76,938,'110 Stawra')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(76,939,'111 Stawra')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(76,940,'215')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(76,941,'112 Stawra')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,942,'Passat')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,943,'Golf')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,944,'Vento')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,945,'Polo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,946,'Corrado')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,947,'Sharan')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,948,'Lupo')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,949,'Bora')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,950,'Jetta')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,951,'New Beetle')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,952,'Phaeton')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,953,'Touareg')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,954,'Touran')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,955,'Multivan')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,956,'Caddy')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,957,'Golf Plus')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,958,'Fox')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,959,'Eos')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,960,'Caravelle')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,961,'Tiguan')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,962,'Transporter')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,963,'Lt')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,964,'Taro')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,965,'Crafter')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,966,'California')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,967,'Santana')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,968,'Scirocco')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,969,'Passat Cc')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,970,'Amarok')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,971,'Beetle')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,972,'Up')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(77,973,'Cc')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,974,'440')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,975,'850')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,976,'S70')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,977,'V70')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,978,'V70 Classic')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,979,'940')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,980,'480')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,981,'460')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,982,'960')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,983,'S90')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,984,'V90')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,985,'Classic')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,986,'S40')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,987,'V40')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,988,'V50')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,989,'V70 Xc')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,990,'Xc70')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,991,'C70')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,992,'S80')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,993,'S60')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,994,'Xc90')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,995,'C30')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,996,'780')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,997,'760')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,998,'740')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,999,'240')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,1000,'360')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,1001,'340')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,1002,'Xc60')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,1003,'V60')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(78,1004,'V40 Cross Country')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(79,1005,'353')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(53,1006,'Mini')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(53,1007,'Countryman')
INSERT INTO Config.CarModel(CarMakeId,CarModelId,Name)VALUES(53,1008,'Paceman')
SET IDENTITY_INSERT Config.CarModel OFF